export const ru_RU: Record<string, string> = {
    'button.ok': 'ОК',
    'button.cancel': 'Отмена',
    'button.back': 'Назад',
    'mainmenu.list.singleplayer': 'Одиночная игра',
    'mainmenu.list.multiplayer': 'Сетевая игра',
    'mainmenu.list.options': 'Настройки',
    'mainmenu.list.about': 'Об игре',
    'mainmenu.list.exit': 'Выход',
    'exitgame.header.title': 'Выход из игры',
    'exitgame.content.message': 'Вы точно хотите выйти из игры?',
    'options.list.gameplay': 'Игра',
    'options.list.graphics': 'Видео и звук',
    'options.list.back': 'Назад',
    'options.gameplay.content.title': 'Настройки игры',
};